# Quantum cryptography


Imports:

In [2]:
# imports
import numpy as np
import pandas as pd
from numpy import random
import scipy
import matplotlib.pyplot as plt
import math
import random

#function

In [25]:
def Random_Alice(length):
    random_bit_alice=np.random.choice(2, length)
    random_base_alice=np.random.choice(2, length)
    print("alice:")
    print(random_bit_alice)
    print(random_base_alice)
    return [random_bit_alice,random_base_alice]
    
def Random_Bob(length):
    random_base_bob=np.random.choice(2, length)
    print("bob:")
    print(random_base_bob)
    return random_base_bob

def matching_bases(alice_bit,alice_base,bob_base,length):
    bob_key=[]
    for i in range (0,length):
        if alice_base[i]==bob_base[i]:
            bob_key.append(alice_bit[i])
    return bob_key


In [26]:
length=10
alice_result=Random_Alice(length)
alice_bit=alice_result[0]
alice_base=alice_result[1]
bob_base=Random_Bob(length)
bob_key=matching_bases(alice_bit,alice_base,bob_base,length)
print("bob Key:")
print(bob_key)

alice:
[0 1 1 0 1 0 0 0 1 0]
[1 0 1 1 1 0 1 1 0 1]
bob:
[1 0 1 1 1 0 0 1 0 1]
bob Key:
[0, 1, 1, 0, 1, 0, 0, 1, 0]


In [27]:
def Random_Eve(length):
    random_base_eve=np.random.choice(2, length)
    print("Eve:")
    print(random_base_eve)
    return random_base_eve

def matching_bases_with_eve(alice_bit,alice_base,bob_base,eve_base,length):
    bob_key_with_eve=[]
    eve_key=[]
    for i in range (0,length):
        if alice_base[i]==bob_base[i]:
            if eve_base[i]==alice_base[i]:
                bob_key_with_eve.append(alice_bit[i])
                eve_key.append(alice_bit[i])
            if eve_base[i]!=alice_base[i]:
                bob_key_with_eve.append(np.random.randint(2))
                eve_key.append(np.random.randint(2))
    return [bob_key_with_eve,eve_key]

In [28]:
length=10
alice_result=Random_Alice(length)
alice_bit=alice_result[0]
alice_base=alice_result[1]
eve_base=Random_Eve(length)
bob_base=Random_Bob(length)
results=matching_bases_with_eve(alice_bit,alice_base,bob_base,eve_base,length)
print("1.bob Key: 2.eve key:")
print(results)

alice:
[1 0 1 0 1 1 1 0 0 0]
[0 1 1 1 0 0 1 1 0 1]
Eve:
[0 1 0 1 0 1 1 0 1 1]
bob:
[1 0 1 0 1 0 1 0 0 0]
1.bob Key: 2.eve key:
[[1, 0, 1, 1], [0, 1, 1, 0]]
